version: 2
updates:
  - package-ecosystem: composer
    directory: /bus_unab
    schedule: { interval: weekly }
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /bus_unab
    schedule: { interval: weekly }
    open-pull-requests-limit: 5
  - package-ecosystem: gradle
    directory: /frontend
    schedule: { interval: weekly }
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: monthly }
